### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by VerstreuteSeele** [Smug246/Luna-Grabber-Builder#2]
Copy-pasting code must be a fun thing to do. I can't even count the number of skids I have found just this month so far.  Why don't you guys just actually learn how to code and come back once you actually understand what you are doing. 

This is an obvious & blatant copy of rdmio's work in combination with some code-fragments that might have been from elsewhere. 

You got 10 hours to remove this repository or it will be reported to Github as distributing malware (regardless of whether it is open-source or not) is against their TOS. If you believe that this will not be effective, ask @H0QLCoder ... oh wait, his account got deleted last morning. oopsie.

~ Clara | CynthiaLabs

**Comment by Smug246** [comment]
i asked rdimo if i could use some of his code as i’m good friends with him so u can calm down as i have his permission lmao

**Comment by Smug246** [comment]
as well as that he may not be a contributor but he helped me on discord with some of the code and cleaning it up.(i'm staff in his server) so before you start crying about something being "skidded" get ur facts right and can i add u also can't read the fact that in the commits i've credited him completely for his injection. So close your issue and have a nice say :)

**Comment by fcliam07** [comment]
How tf do I delete a project.
Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________
From: Clara Crazy ***@***.***>
Sent: Friday, June 3, 2022 5:44:50 AM
To: Smug246/Luna-Grabber-Builder ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Smug246/Luna-Grabber-Builder] :) (Issue #2)


Copy-pasting code must be a fun thing to do. I can't even count the number of skids I have found just this month so far. Why don't you guys just actually learn how to code and come back once you actually understand what you are doing.

This is an obvious & blatant copy of rdmio's work in combination with some code-fragments that might have been from elsewhere.

You got 10 hours to remove this repository or it will be reported to Github as distributing malware (regardless of whether it is open-source or not) is against their TOS. If you believe that this will not be effective, ask @H0QLCoder<https://github.com/H0QLCoder> ... oh wait, his account got deleted last morning. oopsie.

~ Clara | CynthiaLabs

**Comment by l3qso** [comment]
> Copy-pasting code must be a fun thing to do. I can't even count the number of skids I have found just this month so far. Why don't you guys just actually learn how to code and come back once you actually understand what you are doing.
> 
> This is an obvious & blatant copy of rdmio's work in combination with some code-fragments that might have been from elsewhere.
> 
> You got 10 hours to remove this repository or it will be reported to Github as distributing malware (regardless of whether it is open-source or not) is against their TOS. If you believe that this will not be effective, ask @H0QLCoder ... oh wait, his account got deleted last morning. oopsie.
> 
> ~ Clara | CynthiaLabs

ur retarded ngl
